### ISSUE TITLE
 v3.12.1: undefined method html_options for SimpleNavigation::ItemAdapter

### ISSUE THREAD

**Issue by averissimo** [codeplant/simple-navigation#154]
When upgrading my rails 3.2.13 to v3.12.1 the error below shows in every page that renders menus

I had to revert to v.3.11.0

```
undefined method `html_options' for #<SimpleNavigation::ItemAdapter:0x007f2270d2bce0>

framework trace:
/home/.rvm/gems/ruby-1.9.3-p484/bundler/gems/simple-navigation-db7b381693d0/lib/simple_navigation/rendering/renderer/list.rb:32:in `block in list_content'
/home/.rvm/gems/ruby-1.9.3-p484/bundler/gems/simple-navigation-db7b381693d0/lib/simple_navigation/rendering/renderer/list.rb:31:in `map'
/home/.rvm/gems/ruby-1.9.3-p484/bundler/gems/simple-navigation-db7b381693d0/lib/simple_navigation/rendering/renderer/list.rb:31:in `list_content'
/home/.rvm/gems/ruby-1.9.3-p484/bundler/gems/simple-navigation-db7b381693d0/lib/simple_navigation/rendering/renderer/list.rb:23:in `render'
/home/.rvm/gems/ruby-1.9.3-p484/bundler/gems/simple-navigation-db7b381693d0/lib/simple_navigation/core/item_container.rb:106:in `render'
/home/.rvm/gems/ruby-1.9.3-p484/bundler/gems/simple-navigation-db7b381693d0/lib/simple_navigation/rendering/helpers.rb:92:in `render_navigation'
actionpack (3.2.13) lib/abstract_controller/helpers.rb:53:in `render_navigation'
```

**Comment by xskif** [comment]
I have the same issue
`undefined method `html_options=' for #<SimpleNavigation`

version 4.0.3
